/**
 * TilesetRegistry
 *
 * M16: Emerald Jungle Production Tileset Integration
 *
 * Tracks the tileset load state for the current session.
 * Populated by BootScene.create() after the load phase completes.
 * Read by GameScene._buildAssetDebugInfo() to power the F7 panel.
 *
 * Sources:
 *   'production'  — Real PNG loaded from assets/worlds/world01_jungle/tilesets/
 *   'procedural'  — Programmatic placeholder generated by BootScene.generateTilesetTexture()
 *
 * Usage:
 *   // BootScene.create():
 *   TilesetRegistry.record({ source: 'production', width: 1024, ... });
 *
 *   // GameScene._buildAssetDebugInfo():
 *   const ts = TilesetRegistry.info;
 *   return { tilesetSource: ts.source, tilesetWidth: ts.width, ... };
 */

// ─── Types ────────────────────────────────────────────────────────────────────

/** Where the active tileset texture was sourced from. */
export type TilesetSource = 'production' | 'procedural';

/** Snapshot of tileset state after BootScene finishes loading. */
export interface TilesetInfo {
  /** Whether the texture came from a real file or was generated in code. */
  source:          TilesetSource;
  /** Full pixel width of the tileset texture. */
  width:           number;
  /** Full pixel height of the tileset texture. */
  height:          number;
  /** Number of tile columns (width ÷ 32). */
  columns:         number;
  /** Number of tile rows (height ÷ 32). */
  rows:            number;
  /** Total number of tiles in the sheet (columns × rows). */
  tileCount:       number;
  /** Whether the optional animated tile atlas loaded (future artwork slot). */
  animAtlasLoaded: boolean;
  /** Whether the optional decorative tile atlas loaded (future artwork slot). */
  decoAtlasLoaded: boolean;
}

// ─── Defaults ─────────────────────────────────────────────────────────────────

/** Fallback used until BootScene calls TilesetRegistry.record(). */
const PROCEDURAL_DEFAULT: TilesetInfo = {
  source:          'procedural',
  width:           1024,
  height:          32,
  columns:         32,
  rows:            1,
  tileCount:       32,
  animAtlasLoaded: false,
  decoAtlasLoaded: false,
};

// ─── TilesetRegistry ──────────────────────────────────────────────────────────

export class TilesetRegistry {
  private static _info: TilesetInfo = { ...PROCEDURAL_DEFAULT };

  /**
   * Read-only snapshot of the last recorded tileset state.
   * Reflects the active texture for the current game session.
   */
  static get info(): Readonly<TilesetInfo> {
    return TilesetRegistry._info;
  }

  /**
   * Record tileset state after BootScene resolves the load outcome.
   * Call once per session during BootScene.create().
   *
   * @param info  Complete tileset state to store.
   */
  static record(info: TilesetInfo): void {
    TilesetRegistry._info = { ...info };
  }

  /**
   * Reset to the procedural default.
   * Useful for tests or scene restarts that regenerate the tileset.
   */
  static reset(): void {
    TilesetRegistry._info = { ...PROCEDURAL_DEFAULT };
  }
}
